services:
  postgres:
    image: 'postgres:15'
    restart: unless-stopped
    environment:
      - 'POSTGRES_DB=sa-2026'
      - 'POSTGRES_PASSWORD=sa-2026'
      - 'POSTGRES_USER=sa-root'
    ports:
      - '5436:5432'
    volumes:
      - pg_sa_data:/data/postgres
volumes:
  pg_sa_data:
